[auth]
site_url = "http://localhost:5174/#"
additional_redirect_urls = []
enable_refresh_token_rotation = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true
max_frequency = "1m0s"
otp_length = 8

[auth.email.smtp]
host = "smtp.resend.com"
port = 587
user = "resend"
pass = "env(RESEND_API_KEY)"
admin_email = "fidelite@pvg.eu"
sender_name = "Qlima Premium Club"

[functions.notify-new-submission]
enabled = true
verify_jwt = false

[functions.notify-submission-status]
enabled = true
verify_jwt = false
import_map = "./functions/notify-submission-status/deno.json"
entrypoint = "./functions/notify-submission-status/index.ts"

[functions.notify-submission-updated-admin]
enabled = true
verify_jwt = false

[functions.notify-reward-redemption]
enabled = true
verify_jwt = false

[functions.notify-reward-status]
enabled = true
verify_jwt = false

[functions.delete-account]
enabled = true
verify_jwt = true
